  </div>
  <!-- /.content-wrapper -->

<!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      //todo
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2019 <a href="#">iSoft Solutions</a>.</strong> All rights reserved.

    Powered by <a class="footer_links" href="http://httpd.apache.org/">Apache</a> &nbsp;&#177 <a class="footer_links" href="http://mysql.org">MySql</a>&nbsp;&#177
    <a class='footer_links' href='http://php.net'>&nbsp;PHP</a> &nbsp;&#8226;<a class='footer_links' href='http://timeclock.sourceforge.net'>&nbsp;PHP Timeclock&nbsp;1.04</a> &nbsp;&#177 <a class="footer_links" href="http://startbootstrap.com/">SB Admin 2 theme</a> &nbsp;&#177 <a class="footer_links" href="http://getbootstrap.com">Bootstrap</a>

  </footer>
